### PR TITLE
Log the JMX error response as well for later diagnosis

### PR DESCRIPTION
**Pull request by tmuehl**
If a JMX call fails, I (as an operator of Pemetaan) want to know why. So the response message might be really helpful.

@drummerwolli Please review

### CODE REVIEW

**Comment by drummerwolli** [comment]
i get the following:
```
 print("Response: " + response)
TypeError: Can't convert 'dict' object to str implicitly
```

**Comment by drummerwolli** [comment]
```metric + ". Response: " + str(response))```

will help ...

**Comment by tmuehl** [comment]
Ah, ok, it's a `dict`. I am sorry.

**Comment by drummerwolli** [comment]
the line is now too long, the flake8 check is not passing :-(

**Comment by drummerwolli** [comment]
branch is out of date, can you update? then i will merge ...

**Pull request merged**
